import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#08090d" },
  app: { flex: 1, backgroundColor: "#08090d", overflow: "hidden" },
  topbar: {
    minHeight: 64,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.10)",
    backgroundColor: "#0b0d12",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  brandRow: { flexDirection: "row", alignItems: "center", gap: 8, flexShrink: 1 },
  brandMark: { width: 38, height: 38, borderRadius: 13, backgroundColor: "#7654f6", alignItems: "center", justifyContent: "center" },
  brandLetter: { color: "#fff", fontSize: 19, fontWeight: "900" },
  brand: { color: "#f7f8fb", fontSize: 17, fontWeight: "800", letterSpacing: -0.4 },
  subtitle: { color: "#8f96a7", fontSize: 8, fontWeight: "800", letterSpacing: 1.5, marginTop: 1 },
  topActions: { flexDirection: "row", alignItems: "center", gap: 6, flexShrink: 0 },
  iconButton: { width: 36, height: 36, borderRadius: 11, borderWidth: 1, borderColor: "rgba(255,255,255,0.09)", alignItems: "center", justifyContent: "center", backgroundColor: "#151820" },
  iconText: { color: "#e7e9ef", fontSize: 20 },
  primaryButton: { minWidth: 78, height: 38, borderRadius: 12, backgroundColor: "#7654f6", alignItems: "center", justifyContent: "center", paddingHorizontal: 11 },
  primaryButtonText: { color: "#fff", fontSize: 13, fontWeight: "800" },
  secondaryButton: { height: 38, borderRadius: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.12)", backgroundColor: "#171a22", alignItems: "center", justifyContent: "center", paddingHorizontal: 11 },
  secondaryButtonText: { color: "#eceef3", fontSize: 13, fontWeight: "700" },
  buttonPressed: { opacity: 0.72, transform: [{ scale: 0.98 }] },
  buttonMuted: { opacity: 0.35 },
  workspace: { flex: 1, minHeight: 0, flexDirection: "row" },
  workspaceCompact: { flexDirection: "column" },
  editorColumn: { flex: 1, minHeight: 0, backgroundColor: "#0c0e13" },
  canvasStage: { flex: 1, minHeight: 0, marginHorizontal: 12, marginTop: 12, marginBottom: 8, borderRadius: 20, overflow: "hidden", alignItems: "center", justifyContent: "center", backgroundColor: "#11141b", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  emptyState: { width: "88%", maxWidth: 480, minHeight: 210, padding: 24, borderRadius: 22, borderWidth: 1, borderStyle: "dashed", borderColor: "rgba(167,139,250,0.45)", backgroundColor: "rgba(118,84,246,0.08)", alignItems: "center", justifyContent: "center" },
  emptyStatePressed: { backgroundColor: "rgba(118,84,246,0.14)" },
  uploadCircle: { width: 56, height: 56, borderRadius: 18, backgroundColor: "rgba(139,92,246,0.18)", alignItems: "center", justifyContent: "center", marginBottom: 12 },
  uploadIcon: { color: "#c4b5fd", fontSize: 30, fontWeight: "300" },
  emptyTitle: { color: "#f5f6fa", fontSize: 21, fontWeight: "800", letterSpacing: -0.6, textAlign: "center" },
  emptyCopy: { color: "#9aa0af", fontSize: 14, lineHeight: 20, textAlign: "center", marginTop: 8 },
  privateCopy: { color: "#78d99b", fontSize: 12, marginTop: 14, fontWeight: "700" },
  toolRow: { paddingHorizontal: 12, paddingTop: 4, paddingBottom: 10, gap: 8 },
  toolButton: { width: 82, minHeight: 54, borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", backgroundColor: "#151820", alignItems: "center", justifyContent: "center", paddingVertical: 6 },
  toolIcon: { color: "#d6ccff", fontSize: 21, fontWeight: "700" },
  toolCaption: { color: "#9ca2b1", fontSize: 9, fontWeight: "700", marginTop: 2 },
  inspector: { width: 330, maxWidth: "100%", backgroundColor: "#0f1117", borderLeftWidth: StyleSheet.hairlineWidth, borderLeftColor: "rgba(255,255,255,0.09)" },
  inspectorCompact: { width: "100%", height: "39%", minHeight: 260, maxHeight: 360, borderLeftWidth: 0, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "rgba(255,255,255,0.09)", borderTopLeftRadius: 22, borderTopRightRadius: 22, overflow: "hidden" },
  inspectorContent: { paddingHorizontal: 18, paddingTop: 14, paddingBottom: 34 },
  panelHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 14 },
  eyebrow: { color: "#747b8d", fontSize: 9, fontWeight: "900", letterSpacing: 1.4 },
  panelTitle: { color: "#f4f5f8", fontSize: 24, fontWeight: "800", letterSpacing: -0.7, marginTop: 2 },
  resetText: { color: "#a88fff", fontSize: 12, fontWeight: "800" },
  textMuted: { opacity: 0.35 },
  adjustment: { marginBottom: 12 },
  adjustmentHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 2 },
  adjustmentLabel: { color: "#d0d3dc", fontSize: 13, fontWeight: "700" },
  adjustmentValue: { color: "#9da3b2", fontSize: 12, fontVariant: ["tabular-nums"] },
  infoCard: { marginTop: 6, padding: 14, borderRadius: 15, borderWidth: 1, borderColor: "rgba(74,222,128,0.16)", backgroundColor: "rgba(34,197,94,0.06)" },
  infoTitle: { color: "#baf6cd", fontSize: 13, fontWeight: "800" },
  infoCopy: { color: "#9ca6a1", fontSize: 11, lineHeight: 16, marginTop: 4 },
  fileCard: { marginTop: 14, padding: 14, borderRadius: 15, backgroundColor: "#151820", borderWidth: 1, borderColor: "rgba(255,255,255,0.07)" },
  fileName: { color: "#eef0f5", fontSize: 14, fontWeight: "700", marginTop: 8 },
  fileMeta: { color: "#8e95a5", fontSize: 11, marginTop: 4 },
  historyMeta: { color: "#806af0", fontSize: 10, fontWeight: "700", marginTop: 10 },
  offscreenCanvas: { position: "absolute", left: -10000, top: 0, opacity: 0 },
});
