import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#06070a" },
  app: { flex: 1, backgroundColor: "#06070a", overflow: "hidden" },
  topbar: {
    minHeight: 60,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.07)",
    backgroundColor: "#0a0c10",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  brandRow: { flexDirection: "row", alignItems: "center", gap: 8, flexShrink: 1 },
  brandMark: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: "#7957ff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#7957ff",
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
  },
  brandLetter: { color: "#fff", fontSize: 19, fontWeight: "900" },
  brand: { color: "#f7f8fb", fontSize: 17, fontWeight: "900", letterSpacing: -0.55 },
  topActions: { flexDirection: "row", alignItems: "center", gap: 5, flexShrink: 0 },
  iconButton: {
    width: 35,
    height: 35,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#14171e",
  },
  iconText: { color: "#e8e9ef", fontSize: 20 },
  primaryButton: {
    minWidth: 72,
    height: 37,
    borderRadius: 12,
    backgroundColor: "#7957ff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  primaryButtonText: { color: "#fff", fontSize: 13, fontWeight: "900" },
  secondaryButton: {
    height: 37,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    backgroundColor: "#151820",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  secondaryButtonText: { color: "#eef0f6", fontSize: 13, fontWeight: "800" },
  buttonPressed: { opacity: 0.72, transform: [{ scale: 0.975 }] },
  buttonMuted: { opacity: 0.34 },
  workspace: { flex: 1, minHeight: 0, flexDirection: "row", backgroundColor: "#080a0e" },
  workspaceCompact: { flexDirection: "column" },
  editorColumn: { flex: 1, minHeight: 0, backgroundColor: "#080a0e" },
  canvasStage: {
    flex: 1,
    minHeight: 0,
    marginHorizontal: 8,
    marginTop: 8,
    marginBottom: 7,
    borderRadius: 24,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#10131a",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.075)",
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  canvasPressed: { borderColor: "rgba(178,159,255,0.65)" },
  compareBadge: {
    position: "absolute",
    top: 12,
    alignSelf: "center",
    backgroundColor: "rgba(7,8,12,0.78)",
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
  },
  compareText: { color: "#e0dcf5", fontSize: 9, fontWeight: "900", letterSpacing: 0.75 },
  emptyState: {
    width: "88%",
    maxWidth: 500,
    minHeight: 220,
    paddingHorizontal: 24,
    paddingVertical: 28,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "rgba(154,128,255,0.28)",
    backgroundColor: "rgba(121,87,255,0.075)",
    alignItems: "center",
    justifyContent: "center",
  },
  uploadCircle: {
    width: 62,
    height: 62,
    borderRadius: 21,
    backgroundColor: "rgba(121,87,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 15,
  },
  uploadIcon: { color: "#d0c5ff", fontSize: 32, fontWeight: "300" },
  emptyTitle: { color: "#fafaff", fontSize: 23, fontWeight: "900", letterSpacing: -0.75, textAlign: "center" },
  emptyCopy: { color: "#a4a9b7", fontSize: 14, lineHeight: 20, textAlign: "center", marginTop: 8, maxWidth: 300 },
  toolButton: {
    flexGrow: 1,
    minWidth: 92,
    maxWidth: 150,
    minHeight: 66,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "#151820",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
  },
  toolIcon: { color: "#d8ceff", fontSize: 24, fontWeight: "700" },
  toolCaption: { color: "#adb2c0", fontSize: 10, fontWeight: "800", marginTop: 3 },
  inspector: {
    width: 360,
    maxWidth: "100%",
    backgroundColor: "#0e1016",
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: "rgba(255,255,255,0.08)",
  },
  inspectorCompact: {
    width: "100%",
    height: "42%",
    minHeight: 270,
    maxHeight: 430,
    borderLeftWidth: 0,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.09)",
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    overflow: "hidden",
    backgroundColor: "#0e1016",
  },
  inspectorCollapsed: { height: 102, minHeight: 102, maxHeight: 102 },
  sheetHandleArea: { alignItems: "center", paddingTop: 7, paddingBottom: 4 },
  sheetHandle: { width: 44, height: 4, borderRadius: 999, backgroundColor: "#424753" },
  sheetHint: { color: "#7c8291", fontSize: 9, fontWeight: "800", marginTop: 5 },
  tabBar: {
    flexDirection: "row",
    marginHorizontal: 10,
    padding: 4,
    borderRadius: 15,
    backgroundColor: "#151820",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.055)",
  },
  tabButton: { flex: 1, minHeight: 38, borderRadius: 11, alignItems: "center", justifyContent: "center" },
  tabButtonActive: { backgroundColor: "#2d2743" },
  tabText: { color: "#8990a0", fontSize: 11, fontWeight: "900" },
  tabTextActive: { color: "#d4c8ff" },
  panelScroll: { flex: 1 },
  inspectorContent: { paddingHorizontal: 16, paddingTop: 15, paddingBottom: 38 },
  panelHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 13 },
  eyebrow: { color: "#7d8392", fontSize: 9, fontWeight: "900", letterSpacing: 1.3 },
  panelTitle: { color: "#f8f8fb", fontSize: 24, fontWeight: "900", letterSpacing: -0.8, marginTop: 2 },
  resetText: { color: "#b6a4ff", fontSize: 12, fontWeight: "900" },
  textMuted: { opacity: 0.35 },
  adjustment: { marginBottom: 11 },
  adjustmentHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 1 },
  adjustmentName: { flexDirection: "row", alignItems: "center", gap: 9 },
  adjustmentIcon: { width: 20, color: "#c5b6ff", fontSize: 15, textAlign: "center" },
  adjustmentLabel: { color: "#d9dce4", fontSize: 13, fontWeight: "800" },
  adjustmentValue: { color: "#a4aaba", fontSize: 12, fontVariant: ["tabular-nums"], fontWeight: "700" },
  transformGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, justifyContent: "space-between" },
  exportCard: {
    padding: 18,
    borderRadius: 20,
    backgroundColor: "#151820",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  exportTitle: { color: "#fafaff", fontSize: 18, fontWeight: "900", letterSpacing: -0.35 },
  exportCopy: { color: "#a3a9b7", fontSize: 12, lineHeight: 18, marginTop: 7 },
  exportMeta: { color: "#c5b7ff", fontSize: 12, fontWeight: "900", marginTop: 14 },
  exportButton: { marginTop: 16, minHeight: 48, borderRadius: 15, backgroundColor: "#7957ff", alignItems: "center", justifyContent: "center" },
  exportButtonText: { color: "#fff", fontSize: 14, fontWeight: "900" },
  historyMeta: { color: "#9380eb", fontSize: 10, fontWeight: "800", marginTop: 18 },
  toast: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 16,
    minHeight: 50,
    borderRadius: 17,
    backgroundColor: "rgba(27,31,39,0.98)",
    borderWidth: 1,
    borderColor: "rgba(120,217,155,0.25)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  toastText: { color: "#cef8da", fontSize: 12, fontWeight: "900", textAlign: "center" },
  offscreenCanvas: { position: "absolute", left: -10000, top: 0, opacity: 0 },
});
