name: Launch EditMyPic to TestFlight

on:
  push:
    branches: ['main']

jobs:
  build_ios:
    name: Build iOS and deploy API
    type: build
    params:
      platform: ios
      profile: production

  submit_ios:
    name: Send to TestFlight
    needs: [build_ios]
    type: testflight
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
